FROM fedora:$VERSION
LABEL org.opencontainers.image.source="https://github.com/mscherer/fedora_static_web_builder"

RUN dnf install --nodocs --setopt=install_weak_deps=False -y golang skopeo && dnf clean all

COPY build.sh /usr/local/bin/build.sh
COPY main.go /srv/main.go
COPY Dockerfile.go_binary /srv/Dockerfile

ENTRYPOINT ["/bin/bash", "/usr/local/bin/build.sh"]
