FROM fedora:$VERSION
LABEL org.opencontainers.image.source="https://github.com/mscherer/fedora_static_web_builder"
RUN dnf install -y --setopt=install_weak_deps=False --best -y caddy && dnf clean all
EXPOSE 8080
COPY generate_data.sh /usr/local/bin/generate_data.sh
CMD ["/usr/bin/bash", "-x", "/usr/local/bin/generate_data.sh"]

