FROM fedora:$VERSION
LABEL org.opencontainers.image.source="https://github.com/mscherer/fedora_static_web_builder"

RUN dnf install --nodocs --setopt=install_weak_deps=False -y buildah && dnf clean all

COPY build.sh /usr/local/bin/build.sh
COPY Dockerfile.binary /srv/Dockerfile
COPY build.local.sh /usr/local/bin/build.local.sh

ENTRYPOINT ["/bin/bash", "/usr/local/bin/build.sh"]
