FROM docker.io/flyio/flyctl:latest AS fly
LABEL org.opencontainers.image.source="https://github.com/mscherer/various_containers/woodpecker_fly"

FROM busybox:latest
COPY --from=fly /flyctl /bin/fly
RUN mkdir -p /etc/ssl/certs/
COPY --from=fly /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY build.sh /bin/build.sh
ENTRYPOINT ["/bin/sh", "/bin/build.sh"]
