FROM fedora:$VERSION
LABEL org.opencontainers.image.source="https://github.com/mscherer/fedora_static_web_builder"
RUN dnf install --setopt=install_weak_deps=False -y jq curl hugo lftp openssh-clients && dnf clean all
COPY build.sh /usr/local/bin/build.sh
COPY download_zola.sh /usr/local/bin/download_zola.sh
RUN /bin/bash -x /usr/local/bin/download_zola.sh
ENTRYPOINT ["/bin/bash", "/usr/local/bin/build.sh"]
